### ISSUE TITLE
unreachable repo

### ISSUE THREAD

**Issue by JohnConnor1969** [osulibraries/ims#1]
Hello. Tell me please how I can get gem "osul_theme", :git => "git@code.osu.edu:osul-ads/osul-theme-gem.git"

which which is mentioned in the file Gemfile in https://github.com/osulibraries/ims/blob/master/Gemfile

**Comment by electrickite** [comment]
Hi @JohnConnor1969 : The IMS project is no longer developed. It is published to Github for informational purposes only. Ohio State's current digital repository can be found here: https://github.com/osulibraries/dc
