### ISSUE TITLE
rake error

### ISSUE THREAD

**Issue by JohnConnor1969** [osulibraries/ims#2]
C:\xxxxxxxxxx\projects\ims>bundle exec rake db:schema:load
C:/xxxxxxxxxx/ruby/lib/ruby/gems/2.0.0/gems/sufia-models-6.2.0/lib/tasks/sufia-models_tasks.rake:27: warning: already initialized constant FULLTEXT_JARS
C:/xxxxxxxxxx/ruby/lib/ruby/gems/2.0.0/gems/sufia-models-6.2.0/lib/tasks/sufia-models_tasks.rake:27: warning: previous definition of FULLTEXT_JARS was here
rake aborted!

**Comment by electrickite** [comment]
Hi @JohnConnor1969 : The IMS project is no longer developed. It is published to Github for informational purposes only. Ohio State's current digital repository can be found here: https://github.com/osulibraries/dc
